DROP DATABASE IF EXISTS DesafioFULL
CREATE DATABASE DesafioFULL
GO
USE DesafioFULL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Obligators](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[CPF] [nvarchar](max) NULL,
 CONSTRAINT [PK_Obligators] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Titles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] [int] NOT NULL,
	[Interest] [float] NOT NULL,
	[Fine] [float] NOT NULL,
	[QuotaNumbers] [int] NOT NULL,
	[ObligatorId] [int] NOT NULL,
	[OriginalValue] [float] NOT NULL,
 CONSTRAINT [PK_Titles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Titles_ObligatorId] ON [dbo].[Titles]
(
	[ObligatorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Titles]  WITH CHECK ADD  CONSTRAINT [FK_Titles_Obligators_ObligatorId] FOREIGN KEY([ObligatorId])
REFERENCES [dbo].[Obligators] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Titles] CHECK CONSTRAINT [FK_Titles_Obligators_ObligatorId]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Quotas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Number] [int] NOT NULL,
	[Value] [int] NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[TitleId] [int] NOT NULL,
 CONSTRAINT [PK_Quotas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Quotas_TitleId] ON [dbo].[Quotas]
(
	[TitleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Quotas]  WITH CHECK ADD  CONSTRAINT [FK_Quotas_Titles_TitleId] FOREIGN KEY([TitleId])
REFERENCES [dbo].[Titles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Quotas] CHECK CONSTRAINT [FK_Quotas_Titles_TitleId]
GO

INSERT INTO Obligators (Name, CPF)VALUES('João Francisco', 12345678910);
INSERT INTO Titles (Number, Interest, Fine, QuotaNumbers, ObligatorId, OriginalValue) VALUES (101010, 0.01, 0.02, 3, 1, 300);

INSERT INTO Quotas (Number, [Value], [Date], TitleId) VALUES (10, 100, 2020-10-30, 1)
INSERT INTO Quotas (Number, [Value], [Date], TitleId) VALUES (11, 100, 2020-11-30, 1)
INSERT INTO Quotas (Number, [Value], [Date], TitleId) VALUES (12, 100, 2020-12-30, 1)
